format_version: 10
pipelines:
  tools-prometheus:
    group: create
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/tools-promotheus
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test-job:
            timeout: 0
            tasks:
            - exec: { command: ansible-playbook,  arguments: ["-i", "172.31.95.147", "tools.yml", "-e", "tools_name=tools", "-e", "ansible_user=ec2-user",
            "-e", "ansible_password=DevOps321" ], run_if: passed }




