- name: Download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

#- name: unarchive prometheus
#  ansible.builtin.unarchive:
#    src: /opt
#    dest: /opt
#    remote_src: yes

